name: FastAPI CI/CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install Virtualenv
      - name: Install Virtualenv
        run: pip install virtualenv

      # Step 4: Cache Virtual Environment
      - name: Cache Virtualenv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Step 5: Create Virtual Environment if Cache Misses
      - name: Set up Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      # # Step 6: Run Tests
      # - name: Run Tests
      #   run: |
      #     source venv/bin/activate
      #     pytest

      # Step 7: Create archive of dependencies
      - name: Create archive of dependencies
        run: |
          cd ./venv/lib/python3.11/site-packages
          zip -r9 ../../../../api.zip .

      # Step 8: Add API files to Zip file
      - name: Add API files to Zip file
        run: |
          cd ./api
          zip -g ../api.zip -r .

      # Step 9: Upload API Zip Artifact
      - name: Upload API Zip
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Lambda api.zip
        uses: actions/download-artifact@v4
        with:
          name: api
          path: .

      - name: Upload to S3
        run: aws s3 cp api.zip s3://fastapi1234213123/api.zip

      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name fastapiCICD --s3-bucket fastapi1234213123 --s3-key api.zip
